### PR TITLE
Added Java gRPC client samples

### PR DESCRIPTION
**Pull request by oskardudycz**
- Included Java snippets into gRPC docs. See related PR: https://github.com/EventStore/EventStoreDB-Client-Java/pull/55
- Updated import script to take samples from Java client repo 

See a preview: https://deploy-preview-191--developers-eventstore.netlify.app/clients/grpc/getting-started/.

### CODE REVIEW

**Comment by ylorph** [comment]
looks good to me

**Review by ylorph — APPROVED** [review]
Looks good to me

**Comment by mat-mcloughlin** [comment]
still missing this image? 
image

or is it just because its on a branch?

**Review by mat-mcloughlin — DISMISSED** [review]

**Review by ylorph — DISMISSED** [review]
Looks good 
(clcked on the wrong place, hence the re-approve)

**Comment by ylorph** [comment]
> 
> 
> still missing this image?
> image
> 
> or is it just because its on a branch?

@mat-mcloughlin @oskardudycz   maybe that image should just go away, it shows in my browser but then....not sure sure what it means 
image

**Comment by oskardudycz** [comment]
@ylorph @mat-mcloughlin, you need to reapprove the PR, as after my commitment to fixing the image link (https://github.com/EventStore/documentation/pull/191/commits/d08ceac0eb7bf3da984f7db5be18adb84af8e2b3) your approvals were taken out.

obraz

**Review by mat-mcloughlin — DISMISSED** [review]

**Review by ylorph — DISMISSED** [review]

**Review by mat-mcloughlin — APPROVED** [review]

**Review by ylorph — APPROVED** [review]

**Pull request merged**
