### PR TITLE
Reduce noice from notice

### PR DESCRIPTION
**Pull request by stktung**
image

While notices can be useful to inform and warn users, the way it is designed can be annoying since it overlaps with the content there is no way to close it. This can look especially terrible on mobile:

image

Suggestions:
1. Completely remove the notice for any latest LTS.
2. Display the notice for the previous LTS but allow it to be close and never show up again later.
3. Keep the notice for any out of support release.

### CODE REVIEW

**Comment by coloradomorrissey** [comment]
@alexeyzimarev I agree with Stephen that the pop-up can be annoying when looking at documents on anything less than the full screen. Do you have any concerns with the proposed PR?

@stktung Perhaps a middle ground is to have the same` showonce` logic with 24.10. Folks who see it and wish to close the pop-up can do so.

**Comment by teamchong** [comment]
I suggest we moving the 'You are reading...' notice into the sidebar to free up reading space and reduce distraction
An example of this is the [mozilla doc page](https://developer.mozilla.org/en-US/docs/Web/HTML)
Here is a demo of it

https://github.com/user-attachments/assets/3e60ede2-d360-4820-b6f4-2073206a6eab

**Comment by alexeyzimarev** [comment]
I wanted it to be removable only after the click the button (confirm: true). I am fine for it to be completely removed from 24.10, I am not even sure why I added it there.

**Review by coloradomorrissey — APPROVED** [review]

**Comment by coloradomorrissey** [comment]
@stktung If you want to update to remove the "You are reading..." from the 24.10, please do so.

**Comment by stktung** [comment]
> I wanted it to be removable only after the click the button (confirm: true). I am fine for it to be completely removed from 24.10, I am not even sure why I added it there.

@alexeyzimarev I will remove the 24.10 notice. For other versions, I'll make sure `confirm: true` is there.

Since 23.10 is a LTS, I'll set `showonce: true` so that the notice won't keep appearing. But as discussed (offline) with Mark, we will turn `showonce` off few months before it goes out of support.

**Comment by stktung** [comment]
> I suggest we moving the 'You are reading...' notice into the sidebar to free up reading space and reduce distraction An example of this is the [mozilla doc page](https://developer.mozilla.org/en-US/docs/Web/HTML) Here is a demo of it
> 
>  2024-11-15.at.11.59.22.-.Black.Primate.mp4

@teamchong noted and will consider in a future redesign. I also often see drop down version selector in the side bar which is also nice IMO.

**Pull request merged**
