### PR TITLE
Connection string gen

### PR DESCRIPTION
**Pull request by alexeyzimarev**

### CODE REVIEW

**Comment by mat-mcloughlin** [comment]
- doesn't work with JS examples
- I think single-node/multi-node and secure/insecure would be better as toggles similar to gossip as you can't tell that there are other options
- lt doesn't seem to be working with manual and local atm

**Review by ylorph — APPROVED** [review]

**Comment by ylorph** [comment]
just 1 thing we might want to add in the `node Url`
the `cloud` & `specify manually` allow to have esdb+discover:// type of connection string .
`node URL` only creates esdb:// seed based connection, it does work when I put a gossip seed DNS and will populate the connection string according to the resolved addresses for it.

**Comment by alexeyzimarev** [comment]
> just 1 thing we might want to add in the `node Url` the `cloud` & `specify manually` allow to have esdb+discover:// type of connection string . `node URL` only creates esdb:// seed based connection, it does work when I put a gossip seed DNS and will populate the connection string according to the resolved addresses for it.

When the cloud fetch discovers a three-node cluster, it will generate `esdb+discover`. The same is for node URL, it checks the gossip result and detects if there's a cluster or not. The same goes for the manual version. If you choose multi-node cluster and DNS gossip, it will generate `esdb+discover`. If you have a different experience, it must be wrong.

**Comment by ylorph** [comment]
will check my dns settings.

**Pull request merged**
