### PR TITLE
Provide instructions to use Vector

### LINKED ISSUE #443: Document APM configuration (metrics, logs) utilizing public vector and esdb source with example sinks
Self Managed
- Log shipping
- Metrics shipping

Event Store Cloud MESDB
- Remote Metrics shipping
- Note (that this is required temporarily until ESC APM integrations are complete)

### PR DESCRIPTION
**Pull request by YoEight**
Fixes #443

### CODE REVIEW

**Comment by oskardudycz** [comment]
@YoEight, is this PR ready for review? If yes, then it'd be good to provide some context why Vector is used, what's the tool. It doesn't have to be Vector documentation, but the information for the people not familiar with Vector how to use it practically to integrate with their current flow.

**Comment by alexeyzimarev** [comment]
@YoEight it doesn't seem to be related to ES Cloud at all, right? It should be moved to server ops docs.

**Comment by YoEight** [comment]
@oskardudycz Vector is used here because it's what we use internally in ES Cloud and got good results with it. It isn't mandatory in any capacity. There is nothing in our usage of Vector in ES Cloud that makes using Vector for our customers mandatory. In this documentation I provided, I basically laid out what we are doing internally with the tool.

The best place to have documentation on Vector is their website. I make sure to add a link to it in the documentation.

**Comment by YoEight** [comment]
@alexeyzimarev I moved the file to the right directory.
@oskardudycz I updated the Vector link to point to the documentation instead of the GitHub error. It's an oversight. I thought I had already done it.

**Comment by ylorph** [comment]
this should go into the eventStore Repo doc i think

**Comment by alexeyzimarev** [comment]
Implemented in https://github.com/EventStore/EventStore/pull/3306

**Pull request closed without merging**
