### PR TITLE
Update palette.scss

### PR DESCRIPTION
**Pull request by coloradomorrissey**
testing new dark background recommendation

### CODE REVIEW

**Comment by coloradomorrissey** [comment]
updated background for dark mode to `#080b0d`

**Review by George-Payne — COMMENTED** [review]
Not a change from this, but there seems to be mis-matched foreground colors:

image

**Comment by coloradomorrissey** [comment]
I added an issue to take a look at the mismatched fonts

**Comment by coloradomorrissey** [comment]
@George-Payne or @stktung would someone approve this PR?  I'll look into the mismatched colors (and alignment) on the landing page, but getting the background color update seems worthwhile.

**Review by George-Payne — APPROVED** [review]

**Pull request merged**
